config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: [:show, :create, :edit, :update]
  resources :games, only: [:new, :index, :show, :destroy]
  resources :comments, only: [:new, :create, :destroy, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image 
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    games_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to games_path, notice: 'You have created comment successfully.'
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    
    if @comment.user != current_user
      redirect_to games_path
    end

  end
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to games_path, notice: 'You have updated comment successfully.'
    else
      render :edit
    end 
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to games_path
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @comment = Comment.new
    @comments = Comment.all
  end



  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
    
    if @user != current_user
      redirect_to games_path
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to games_path, notice: 'You have updated user successfully.'
    else 
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container px-5 px-sm-0 mx-15">

      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>Editing Comment</h2>
        <% if @comment.errors.any? %>
          <h3><%= @comment.errors.count %>errors prohibited this obj from being saved:</h>
          <ul>
          <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
        <%= form_with model:@comment, local:true do |f| %>
          <div class="form-group">
            <label for="comment">Comment Text</label>
            <%= f.text_field :title, autofocus: true, class: "form-control name" %>
          </div>

          <div class="form-group">
            <%= f.submit "Update Comment", class: "btn btn-secondary" %>
          </div>
        <% end %>
        <p> 
          <%= link_to "Back", games_path %>
        </p>
      </div>
  </div>
</main>

app/views/games/index.html.erb
<main>
  <div class='container px-5 px-sm-0'>
    <div class="row">
      <div class='col-md-8 offset-md-1'>
        <h2>GameList</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>Title</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td></td>
              <td>
                <%= link_to games_path do %>
                  <h4>play</h4>
                <% end %>
              </td>
              <td></td>
            </tr>
          </tbody>
        </table>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>Comment</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @comments.each do |comment| %>
            <tr>
              <td><%= comment.user.name %></td>
              <td><%= comment.comment %></td>
              <td><% if @comment.user == current_user %>
                    <%= link_to "Edit",edit_comment_path(@comment), class: "btn btn-secondary" %>
                  <% end %></td>
              <td><% if @comment.user == current_user %>
                    <%= link_to "Destroy", comment_path(@comment), class: "btn btn-sm btn-danger", method: :delete %>
                  <% end %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>Create Comment</h2>
          <%= form_with model:@comment, local:true do |f| %>
            <div class="form-group">
              <label for="comment_comment">Comment</label>
              <%= f.text_field :comment, autofocus: true, class: "form-control name" %>
            </div>
            <div class="form-group">
              <%= f.submit "Create Comment", class: "btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/games/show.html.erb
<h1>ここにゲーム</h1>

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to 
          <strong>GameCenter</strong>!!
        </h1>
        <p>In 
          <strong>GameCenter</strong>,
        </p>
        <p>"Let's enjoy!!"</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>GameCenter</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

          <% if user_signed_in? %>

          <li>
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
          <%= link_to edit_user_path(current_user), class: "nav-link text-light" do %>
            <i class="fas fa-user-cog"></i>Edit User
          <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i>Log out
            <% end %>
          </li>
          <% else %>
          <li>
            <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %> 
          </li>
          <li>
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i>Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i>Log in
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameCenter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container px-5 px-sm-0 mx-15">

      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control name" %>
          </div>

          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
  </div>
</main>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>